// Определите функции для решение алгебраических уравнений

let dichotomy f a b = 0.

let iterations phi x0 = 0.

let newthon f f' x0 = 0.
// используйте функцию 'iterations'

// Решите 3 уравнения (начиная со своего номера варианта) с использованием 3-х методов
let f1 = ...
let f2 = ...
let f3 = ...

let f1' = ...
let f2' = ...
let f3' = ...

let phi1 = ...
let phi2 = ...
let phi3 = ...

let main = 
    printfn "%10.5f  %10.5f  %10.5f" (dichotomy f1 0. 1.) (iterations phi1 0.) (newthon f1 f1' 1.)
    printfn "%10.5f  %10.5f  %10.5f" (dichotomy f2 0. 1.) (iterations phi2 0.) (newthon f2 f2' 1.)
    printfn "%10.5f  %10.5f  %10.5f" (dichotomy f3 0. 1.) (iterations phi3 0.) (newthon f3 f3' 1.)

 